[project]
name = "sandwich"
version = "0.0.1"
description = "A TUI Project Management Software made with Python."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyinstaller>=6.18.0",
    "textual>=7.3.0",
]
